import type { CSSProperties } from "react";
import {
  appShellRecipe,
  badgeRecipe,
  buttonRecipe,
  cardRecipe,
  componentRecipe,
  designTokens,
  inputRecipe,
  overlayRecipe,
  tableRecipe,
} from "../generated/styling";

export function themeVariables(): CSSProperties & Record<`--${string}`, string | number> {
  return {
    "--page-bg": componentRecipe.page.background,
    "--canvas-bg": appShellRecipe.mainBackground,
    "--surface-bg": componentRecipe.card.background,
    "--surface-hover": designTokens.rawColors.background.surfaceHover,
    "--surface-selected": designTokens.rawColors.background.surfaceSelected,
    "--primary-text": componentRecipe.page.color,
    "--secondary-text": designTokens.colors.secondaryText,
    "--placeholder-text": designTokens.colors.placeholderText,
    "--inverse-text": designTokens.rawColors.foreground.inverse,
    "--brand": designTokens.colors.brand,
    "--brand-hover": designTokens.rawColors.brand.hover,
    "--brand-surface": appShellRecipe.activeNavBackground,
    "--brand-border": designTokens.rawColors.brand.border,
    "--border": designTokens.colors.border,
    "--border-subtle": designTokens.colors.headerBorder,
    "--border-hover": designTokens.rawColors.border.hover,
    "--focus-ring": designTokens.colors.focusRing,
    "--primary-button-bg": buttonRecipe.primary.background,
    "--primary-button-hover": String(buttonRecipe.primary.hoverBackground),
    "--primary-button-active": String(buttonRecipe.primary.activeBackground),
    "--primary-button-text": buttonRecipe.primary.color,
    "--secondary-button-bg": buttonRecipe.secondary.background,
    "--secondary-button-text": buttonRecipe.secondary.color,
    "--secondary-button-border": designTokens.rawColors.button.secondaryBorder,
    "--secondary-button-hover-border": String(buttonRecipe.secondary.hoverBorderColor),
    "--secondary-button-active-bg": String(buttonRecipe.secondary.activeBackground),
    "--disabled-bg": String(buttonRecipe.primary.disabledBackground),
    "--disabled-text": String(buttonRecipe.primary.disabledColor),
    "--danger-bg": buttonRecipe.dangerPrimary.background,
    "--danger-hover": String(buttonRecipe.dangerPrimary.hoverBackground),
    "--danger-active": String(buttonRecipe.dangerPrimary.activeBackground),
    "--danger-text": buttonRecipe.dangerPrimary.color,
    "--danger-soft": badgeRecipe.danger.background,
    "--danger-fg": designTokens.rawColors.semantic.danger.fg,
    "--success-soft": badgeRecipe.success.background,
    "--success-fg": badgeRecipe.success.color,
    "--info-soft": badgeRecipe.info.background,
    "--info-fg": badgeRecipe.info.color,
    "--input-bg": inputRecipe.default.background,
    "--input-border": designTokens.rawColors.border.default,
    "--input-active-bg": designTokens.rawColors.background.searchActive,
    "--card-radius": `${cardRecipe.default.borderRadius}px`,
    "--modal-radius": `${overlayRecipe.modal.borderRadius}px`,
    "--button-radius": `${buttonRecipe.primary.borderRadius}px`,
    "--input-radius": `${inputRecipe.default.borderRadius}px`,
    "--badge-radius": `${badgeRecipe.info.borderRadius}px`,
    "--button-height": `${buttonRecipe.primary.minHeight}px`,
    "--input-height": `${inputRecipe.default.minHeight}px`,
    "--sidebar-width": `${appShellRecipe.sidebarWidth}px`,
    "--modal-shadow": overlayRecipe.modal.boxShadow,
    "--popover-shadow": overlayRecipe.toast.boxShadow,
    "--table-header-bg": tableRecipe.header.background,
    "--table-row-border": tableRecipe.row.borderBottom,
    "--table-row-hover": tableRecipe.row.hoverBackground,
    "--motion-hover": designTokens.motion.hover,
    "--motion-base": designTokens.motion.base,
    "--font-product": `${designTokens.typography.fontFamily}, Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif`,
    "--font-mono": `${designTokens.typography.raw.mono.family}, "SFMono-Regular", Consolas, "Liberation Mono", monospace`,
  };
}
